services:
  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: healthcare-wiremock
    ports:
      - "8090:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    command: --global-response-templating --verbose
