
services:
  healthcare-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: healthcare-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - healthcare_zookeeper_data:/var/lib/zookeeper/data
      - healthcare_zookeeper_log:/var/lib/zookeeper/log
    networks:
      - healthcare-network

  healthcare-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: healthcare-kafka
    depends_on:
      - healthcare-zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: healthcare-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://healthcare-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - healthcare_kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - healthcare-network

  healthcare-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: healthcare-kafka-ui
    depends_on:
      - healthcare-kafka
    ports:
      - "8086:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: healthcare-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: healthcare-kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: healthcare-zookeeper:2181
    networks:
      - healthcare-network

volumes:
  healthcare_zookeeper_data:
  healthcare_zookeeper_log:
  healthcare_kafka_data:

networks:
  healthcare-network:
    name: healthcare-network
    external: true